# Generated by Django 2.2 on 2019-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabaitSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbysupplier',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
