# Generated by Django 2.2 on 2019-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabaitSystem', '0002_auto_20190507_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbysupplier',
            name='makat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productbysupplier',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
