# Generated by Django 2.2 on 2019-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabaitSystem', '0003_auto_20190516_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_in_zap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('makat', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
