# Generated by Django 2.2 on 2019-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BabaitSystem', '0004_product_in_zap'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_in_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makat', models.CharField(default='', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product_in_zap',
            options={'verbose_name': 'מוצרים בזאפ', 'verbose_name_plural': 'מוצרים בזאפ'},
        ),
        migrations.AlterModelOptions(
            name='productbysupplier',
            options={'verbose_name': 'מוצרים לפי ספקים', 'verbose_name_plural': 'מוצרים לפי ספקים'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'מוצרים', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'ספקים', 'verbose_name_plural': 'ספקים'},
        ),
        migrations.AddField(
            model_name='productbysupplier',
            name='is_price_up',
            field=models.BooleanField(default=False),
        ),
    ]
