# Generated by Django 2.2 on 2019-06-13 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BabaitSystem', '0005_auto_20190613_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='price_in_pass',
            new_name='price_in_past',
        ),
    ]
